"""
================================================================================
Q2 - Books of Ice and Fire
================================================================================
Tasks:
    a. Read list of books from API
    b. Create dictionary of {book_name: [pages, date_of_release, ISBN, publisher]}
    c. Create a CSV file with this dictionary

API URL : https://anapioficeandfire.com/api/books
Author  : Calsoft Internship Assignment 2026
================================================================================
"""

import requests
import csv
import logging
from datetime import datetime

# ── Logging Setup ─────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)s]  %(message)s",
    datefmt="%H:%M:%S"
)
log = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────
BASE_URL = "https://anapioficeandfire.com/api/books"
OUT_CSV  = "Q2_books_output.csv"


# ══════════════════════════════════════════════════════════════════════════════
#  a. Fetch all books from API
# ══════════════════════════════════════════════════════════════════════════════

def fetch_all_books() -> list[dict]:
    """
    Fetches all books from the Ice and Fire API.
    Handles pagination via the Link header.

    Returns:
        List of raw book dicts from the API.
    """
    books = []
    page  = 1

    log.info("Fetching books from API...")

    while True:
        response = requests.get(BASE_URL, params={"page": page, "pageSize": 50}, timeout=15)
        response.raise_for_status()

        batch = response.json()
        if not batch:
            break

        books.extend(batch)
        log.info(f"  Page {page} fetched  |  Total books so far: {len(books)}")

        if 'rel="next"' not in response.headers.get("Link", ""):
            break
        page += 1

    log.info(f"Fetch complete. Total books: {len(books)}")
    return books


# ══════════════════════════════════════════════════════════════════════════════
#  b. Build dictionary  {book_name: [pages, date_of_release, ISBN, publisher]}
# ══════════════════════════════════════════════════════════════════════════════

def format_date(raw_date: str) -> str:
    """
    Converts ISO 8601 date string to a readable format (YYYY-MM-DD).

    Args:
        raw_date: e.g. '1996-08-01T00:00:00'

    Returns:
        Formatted date string, e.g. '1996-08-01'
    """
    if not raw_date:
        return "N/A"
    try:
        dt = datetime.fromisoformat(raw_date.replace("Z", ""))
        return dt.strftime("%Y-%m-%d")
    except ValueError:
        return raw_date[:10] if len(raw_date) >= 10 else raw_date


def build_books_dict(books: list[dict]) -> dict[str, list]:
    """
    Builds a dictionary mapping each book's name to its key details.

    Structure:
        {
            "A Game of Thrones": [694, "1996-08-01", "978-0553103540", "Bantam Books"],
            ...
        }

    Args:
        books: Raw list of book dicts from the API.

    Returns:
        Dictionary {book_name: [pages, date_of_release, ISBN, publisher]}
    """
    books_dict = {}

    for book in books:
        name      = book.get("name")        or "Unknown Title"
        pages     = book.get("numberOfPages", 0)
        released  = format_date(book.get("released", ""))
        isbn      = book.get("isbn")        or "N/A"
        publisher = book.get("publisher")   or "N/A"

        books_dict[name] = [pages, released, isbn, publisher]
        log.info(f"  Added: {name}  |  Pages: {pages}  |  ISBN: {isbn}")

    return books_dict


# ══════════════════════════════════════════════════════════════════════════════
#  c. Write dictionary to CSV
# ══════════════════════════════════════════════════════════════════════════════

def write_to_csv(books_dict: dict[str, list], filepath: str) -> None:
    """
    Writes the books dictionary to a well-formatted CSV file.

    CSV columns: Book Name, Number of Pages, Date of Release, ISBN, Publisher

    Args:
        books_dict: {book_name: [pages, date_of_release, isbn, publisher]}
        filepath  : Output CSV file path.
    """
    headers = ["Book Name", "Number of Pages", "Date of Release", "ISBN", "Publisher"]

    with open(filepath, "w", newline="", encoding="utf-8") as csvfile:
        writer = csv.writer(csvfile)

        # Metadata header rows
        writer.writerow(["# Books of Ice and Fire – Generated by Q2_books.py"])
        writer.writerow([f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"])
        writer.writerow([f"# Total Books: {len(books_dict)}"])
        writer.writerow([])          # blank separator row

        # Column headers
        writer.writerow(headers)

        # Data rows
        for book_name, details in books_dict.items():
            pages, released, isbn, publisher = details
            writer.writerow([book_name, pages, released, isbn, publisher])

    log.info(f"CSV written: {filepath}  ({len(books_dict)} rows)")


# ══════════════════════════════════════════════════════════════════════════════
#  Main
# ══════════════════════════════════════════════════════════════════════════════

def main():
    print("\n" + "═" * 60)
    print("   Q2 – BOOKS OF ICE AND FIRE")
    print("═" * 60)

    # a. Fetch
    raw_books = fetch_all_books()

    # b. Build dictionary
    books_dict = build_books_dict(raw_books)
    log.info(f"Dictionary built with {len(books_dict)} entries.")

    # c. Write CSV
    write_to_csv(books_dict, OUT_CSV)

    # Console preview
    print("\n  ┌──────────────────────────────────────────────────────────────────────────┐")
    print("  │  BOOKS DICTIONARY PREVIEW                                                │")
    print("  ├──────────────────────────────────────────┬───────┬────────────┬──────────┤")
    print(f"  │ {'Book Name':<42}│ {'Pages':<6}│ {'Released':<11}│ {'Publisher':<9}│")
    print("  ├──────────────────────────────────────────┼───────┼────────────┼──────────┤")
    for name, (pages, released, isbn, publisher) in books_dict.items():
        print(f"  │ {name[:41]:<42}│ {str(pages):<6}│ {released:<11}│ {publisher[:8]:<9}│")
    print("  └──────────────────────────────────────────┴───────┴────────────┴──────────┘")

    print(f"\n  ✔  Done!  {len(books_dict)} books saved to → {OUT_CSV}\n")

    # Print full dictionary to console
    print("  Full Dictionary:")
    print("  " + "-" * 56)
    for book_name, details in books_dict.items():
        print(f"  {book_name}")
        print(f"    Pages    : {details[0]}")
        print(f"    Released : {details[1]}")
        print(f"    ISBN     : {details[2]}")
        print(f"    Publisher: {details[3]}")
        print()


if __name__ == "__main__":
    main()
